//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Sdt { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Addres { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
